name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check format
      run: cargo fmt --check

    - name: Check code
      run: cargo clippy

    - name: Run tests
      run: cargo test --verbose
